# -*- coding: utf-8 -*-
"""Read-FFT-Dims.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W8ESXVdXjs41m2lMZER1o6UaYW2lZZbB
"""

import librosa
from google.colab import drive
drive.mount('/content/drive')
import numpy as np
import matplotlib.pyplot as plt

def getFFT(input, size = 2048):
  y, sr = librosa.load(input)
  S = np.abs(librosa.stft(y = y, n_fft=size))
  out = S[10:100]
  np.savetxt('new.csv', out, delimiter=',')
  return out
  #print(out.shape, 'mean:', np.mean(out), 'max:', np.max(out), 'median:', np.median(out))

#might want to look into stft params more

out = getFFT(insertYourTrack)
#goldenOut = getFFT(golden)

def setDims(FFT):
  width = FFT.shape[1]
  if ((FFT.shape[0])<(width*0.56)):
    height = int(width*0.56)
  else:
    height = FFT.shape[0]
  return width, height

setDims(out)